spring.application.name=WALLETIX_Gustabo
spring.jpa.database = postgresql
sping.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/[NombreBD]
spring.datasource.username=postgres
spring.datasource.password=Gust@bo2024